// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX-YpX5RMG9_x5tSjb2THhO0Q6rsu6Xro',
    appId: '1:404918018084:android:7bee72fa5d44b42665b8b1',
    messagingSenderId: '404918018084',
    projectId: 'freedom-transport-4db68vr',
    databaseURL: 'https://freedom-transport-4db68vr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'freedom-transport-4db68vr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpb_4z0yaIfBIYXa-odeMNxEXvg6GVzEE',
    appId: '1:404918018084:ios:1f611159460a474265b8b1',
    messagingSenderId: '404918018084',
    projectId: 'freedom-transport-4db68vr',
    databaseURL: 'https://freedom-transport-4db68vr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'freedom-transport-4db68vr.appspot.com',
    androidClientId: '404918018084-fqsq61ndh6c4isvogndbulc5s1hqldkl.apps.googleusercontent.com',
    iosClientId: '404918018084-ghodamrurd157kqpjaos862qmspi93lc.apps.googleusercontent.com',
    iosBundleId: 'com.freedomtransportdriver.app',
  );
}
